# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_check.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_check.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10user_check.proto\x12\tusercheck\"%\n\x11UserExistsRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"$\n\x12UserExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32]\n\x0bUserChecker\x12N\n\x0f\x43heckUserExists\x12\x1c.usercheck.UserExistsRequest\x1a\x1d.usercheck.UserExistsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_check_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USEREXISTSREQUEST']._serialized_start=31
  _globals['_USEREXISTSREQUEST']._serialized_end=68
  _globals['_USEREXISTSRESPONSE']._serialized_start=70
  _globals['_USEREXISTSRESPONSE']._serialized_end=106
  _globals['_USERCHECKER']._serialized_start=108
  _globals['_USERCHECKER']._serialized_end=201
# @@protoc_insertion_point(module_scope)
