# В этом месте вам необходимо настроить маршрутизацию /api/<resource>
server {
    listen 80;
    server_name localhost;

    location /api/logs {
        rewrite ^/api/logs(.*)$ /logs$1 break;
        
        proxy_pass http://service-logs:8219;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/other {
        rewrite ^/api/other(.*)$ /other$1 break;
        proxy_pass http://service-other:8219;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}