upstream comments-upstream {
    server comments-svc-s19:8138;
}

upstream users-upstream {
    server users-svc-s19:8090;
}

server {
    listen 80;
    server_name localhost;

    location /api/comments {
        rewrite ^/api/comments(.*)$ /comments$1 break;
        proxy_pass http://comments-upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/users {
        rewrite ^/api/users(.*)$ /users$1 break;
        proxy_pass http://users-upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
