# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0b\x63omments.v1\"\x1c\n\x0e\x43ommentRequest\x12\n\n\x02id\x18\x01 \x01(\t\";\n\x0f\x43ommentResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t2Z\n\x0f\x43ommentsService\x12G\n\nGetComment\x12\x1b.comments.v1.CommentRequest\x1a\x1c.comments.v1.CommentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMENTREQUEST']._serialized_start=30
  _globals['_COMMENTREQUEST']._serialized_end=58
  _globals['_COMMENTRESPONSE']._serialized_start=60
  _globals['_COMMENTRESPONSE']._serialized_end=119
  _globals['_COMMENTSSERVICE']._serialized_start=121
  _globals['_COMMENTSSERVICE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
